### ISSUE TITLE
黑夜模式的png似乎不会更改。

### ISSUE THREAD

**Issue by ArtisanMinds** [U8F69/open-webui#79]
_dark部分只给了png，切换到黑夜模式的时候图片没有更改，或是说需要别的设置
设置如下
```yaml

version: '3.8'
services:
  open-webui:
    image: ghcr.io/u8f69/open-webui:v0.6.5.46
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - LICENSE_KEY=enterprise
      - ORGANIZATION_NAME=Wanglab AI
      - CUSTOM_NAME=Wanglab AI
      - CUSTOM_ICO=http://host.docker.internal:18080/wanglab.ico
      - CUSTOM_PNG=http://host.docker.internal:18080/wanglab.png
      - CUSTOM_DARK_PNG=http://host.docker.internal:18080/wanglab_dark.png  # 切换到黑夜模式没有变化
      - CUSTOM_SVG=http://host.docker.internal:18080/wanglab.svg
      - CREDIT_NO_CREDIT_MSG="余额不足，请联系管理员"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  open-webui:

```
